#services:
#  - docker

#before_install:
#- docker pull parthikmodi/texttrackservice_website
#- docker run -d -p 127.0.0.1:80:4567 parthikmodi/texttrackservice_website /bin/sh 
#- docker ps -a
#- docker run parthikmodi/texttrackservice_website /bin/sh 

#script:
#- docker-compose exec --user "$(id -u):$(id -g)" website rails db:reset
sudo: required
language: ruby
rvm:
  - 2.5.7


services:
  - docker

env:
  global:
    - IMAGE_NAME=parthikmodi/tts
    - DOCKER_PASSWORD=Docker@10

script:
  - docker-compose up --build -d

after_script:
  - docker images

before_deploy:
  - git add .
  - git commit -m "commit from travis-ci"
  - git push origin master
  - docker login -u "parthikmodi" -p "$DOCKER_PASSWORD"
  - id = docker images --format="{{.Repository}} {{.ID}}" | grep "parthikmodi/tts " | cut -d' ' -f2)
  - docker commit ${id} tts
  - docker tag tts ${IMAGE_NAME}
  - docker push ${IMAGE_NAME}

deploy:
  provider: script

  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master