#services:
#  - docker

#before_install:
#- docker pull parthikmodi/texttrackservice_website
#- docker run -d -p 127.0.0.1:80:4567 parthikmodi/texttrackservice_website /bin/sh 
#- docker ps -a
#- docker run parthikmodi/texttrackservice_website /bin/sh 

#script:
#- docker-compose exec --user "$(id -u):$(id -g)" website rails db:reset
sudo: required
language: ruby


services:
  - docker

env:
  global:
    - IMAGE_NAME=parthikmodi/tts
    - DOCKER_PASSWORD=Docker@10

before_script:
  - version="$(awk '$2 == "CAKE_SERVICE_VERSION" { print $3; exit }' Dockerfile)"
  - docker pull "$IMAGE_NAME" || true

script:
  - docker run parthikmodi/tts /bin/sh -c "cd /text-track-service"

after_script:
  - docker images

before_deploy:
  - docker login -u "parthikmodi" -p "$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - git add .
  - git commit -m "commit from travis-ci"
  - git push

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master