services:
  - docker

before_install:
- docker pull silentflame/tts-docker
- docker run -d -p 127.0.0.1:80:4567 silentflame/tts-docker /bin/sh 
- docker ps -a
- docker run silentflame/tts-docker /bin/sh 

script:
- bundle exec rake test