#services:
#  - docker

#before_install:
#- docker pull parthikmodi/texttrackservice_website
#- docker run -d -p 127.0.0.1:80:4567 parthikmodi/texttrackservice_website /bin/sh 
#- docker ps -a
#- docker run parthikmodi/texttrackservice_website /bin/sh 

#script:
#- docker-compose exec --user "$(id -u):$(id -g)" website rails db:reset

language: ruby

services:
  - docker

before_install:
- docker pull parthikmodi/tts
- docker run -d -p 127.0.0.1:80:4567 parthikmodi/tts /bin/sh -c "cd /text-track-service; bundle exec foreman start;"
- docker ps -a
- docker run parthikmodi/tts /bin/sh -c "cd /text-track-service"
